### ISSUE TITLE
Diesel icon missing

### ISSUE THREAD

**Issue by pogobanane** [foxholetools/assets#1]
I believe the diesel icon is missing in this repo.
https://raw.githubusercontent.com/the-fellowship-of-the-warapi/Assets/master/Item Icons/Materials/ResourceFuelIcon.png

**Comment by samuelds** [comment]
Icon found on `Textures\War\Content\Slate\Images` on the game pak, what the logic

**Comment by samuelds** [comment]
Fixed https://github.com/foxholetools/assets/commit/f5403fcb9e3d9152f99027b76d1028720d3be856

**Comment by pogobanane** [comment]
<3 please also publish to gh-pages

**Comment by samuelds** [comment]
Project so big for use gh-pages
