### ISSUE TITLE
Extract Item Names

### ISSUE THREAD

**Issue by GICodeWarrior** [foxholetools/assets#2]
Is it possible to extract the item names and descriptions?

For example, lightartilleryammoitem.png is "120mm" and clothitem.png is "Soldier Supplies"

**Comment by samuelds** [comment]
Hello,

The file names are the original names of the game.

**Comment by GICodeWarrior** [comment]
I've written a hacky script to extract information like the below out of the uasset files.

```JSON
{
  "/Game/Textures/UI/ItemIcons/GrenadeItemIcon": {
    "strings": [
      "Grenade",
      "A3 Harpa Fragmentation Grenade",
      "This anti-personnel fragmentation grenade is designed with pull-pin mechanics and a timed fuse for user safety. Serrations in the casing allow for a better grip and increased fragmentation effectiveness."
    ],
    "source": "War/Content/Blueprints/ItemPickups/GrenadeWPickup.uasset"
  },
  "/Game/Textures/UI/ItemIcons/HeavyArtilleryAmmoItemIcon": {
    "strings": [
      "150mm",
      "Payload for heavy artillery weapons."
    ],
    "source": "War/Content/Blueprints/ItemPickups/HeavyArtilleryAmmoPickup.uasset"
  },
  "/Game/Textures/UI/ItemIcons/LightArtilleryAmmoItemIcon": {
    "strings": [
      "120mm",
      "Payload for light artillery weapons."
    ],
    "source": "War/Content/Blueprints/ItemPickups/LightArtilleryAmmoPickup.uasset"
  },
  "/Game/Textures/UI/ItemIcons/MachineGunAmmoIcon": {
    "strings": [
      "12.7mm",
      "Standard ammunition for all machine guns, including vehicle mounted weapons like those on the Half-Track and Battle Tank."
    ],
    "source": "War/Content/Blueprints/ItemPickups/MachineGunAmmoPickup.uasset"
  },
  "/Game/Textures/UI/ItemIcons/MortarItemIcon": {
    "strings": [
      "Mortar",
      "Cremari Mortar",
      "This short-range cannon is designed to bombard enemy infantry with indirect fire."
    ],
    "source": "War/Content/Blueprints/ItemPickups/MortarPickup.uasset"
  }
}
```

It's not complete though.  If anyone knows or finds a better way, please let me know.

**Comment by GICodeWarrior** [comment]
In case others are looking, FModel reads the Foxhole uasset files well to extract the names, descriptions and more.
https://github.com/iAmAsval/FModel

**Comment by pogobanane** [comment]
@GICodeWarrior i extracted most of my files via https://github.com/pogobanane/foxhole-iconpacks#extracting-icons-from-mods

for foxhole-screenparse i am manually writing a mapping, because even in the original game files there are way too many exceptions and spelling errors than you could generate filenames reasonably by a script. https://github.com/pogobanane/foxhole-screenparse/blob/main/items.js

 (imgName -> foxholelogi.com; imgPath -> github.com/foxholetools/assets/dist; imgUasset -> github.com/pogobanane/foxhole-iconpacks/mods/*/)
